### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by manisaiprasad** [dscjntuc/Data-Structures-and-Algorithms#7] opened 2020-09-30 17:45 UTC
Update Readme.md according to the programs in the repository

**Comment by charchitmangal** [comment] 2020-09-30 21:16
Hello! pls assign it to me

**Comment by aaishikasb** [comment] 2020-10-01 07:28
Hello, if the issue is still open, I would like to work on it.

**Comment by manisaiprasad** [comment] 2020-10-01 11:51
@charchithere @aaishikasb There is a lot 
You can do at Readme, So show your creativity

**Comment by gaurang7goel** [comment] 2020-10-01 12:52
Hi, is the issue still open , if yes then I am ready to contribute in it.

**Closed as completed** 2020-10-03 17:32 UTC
Labels: documentation, good first issue, help wanted, Hacktoberfest
